# This sample sets up an Elasticsearch cluster with 3 nodes.
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 8.12.2
  nodeSets:
    - name: hot
      config:
        # most Elasticsearch configuration parameters are possible to set, e.g: node.attr.attr_name: attr_value
        node.roles: ["master", "data_hot", "ingest", "ml"]
        node.store.allow_mmap: false
      podTemplate:
        metadata:
          labels:
            # additional labels for pods
            app.kubernetes.io/name: elasticsearch
        spec:
          containers:
            - name: elasticsearch
              # specify resource limits and requests
              resources:
                limits:
                  memory: 4Gi
                  cpu: 1
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms2g -Xmx2g"
      count: 3
    - name: cold
      config:
          node.roles: ["data_cold"]
          node.store.allow_mmap: false
      podTemplate:
          metadata:
            labels:
              app.kubernetes.io/name: elasticsearch
              data-tiers: cold
          spec:
            containers:
              - name: elasticsearch
                resources:
                  limits:
                    memory: 4Gi
                    cpu: 1
                env:
                  - name: ES_JAVA_OPTS
                    value: "-Xms2g -Xmx2g"
      count: 1
    - name: frozen
      config:
        node.roles: [ "data_frozen" ]
        node.store.allow_mmap: false
        podTemplate:
          metadata:
            labels:
              app.kubernetes.io/name: elasticsearch
              data-tiers: cold
          spec:
            containers:
              - name: elasticsearch
                resources:
                  limits:
                    memory: 4Gi
                    cpu: 1
                env:
                  - name: ES_JAVA_OPTS
                    value: "-Xms2g -Xmx2g"
        count: 1
